name = "Vanilla + for Sunny"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2312f1b7cbb0a841da169ca6ac857092d2eecb4b79dd8ec2b53ac6071868926"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
