name = "Vanilla + for Sunny"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e95ca96473d923cbd82a434dc5071f0e2c0a13538a164df6f8fc1afc7428c49"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
