name = "Vanilla + for Sunny"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8530a91b3cc709dfc12ba433174832d0d56abdb3fd8886becf30069449e93437"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
