name = "Vanilla + for Sunny"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cef6019833421b7ab04c3ba510425ee426af3c41b72ce4a592182ce207b70024"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
