name = "Vanilla + for Sunny"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0aac2343f07e6a11fd7fe20d18be8147b499d9efddd35a5102b05b181355ac5c"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
