name = "Vanilla + for Sunny"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b58fd94e9b05a919185156a35d6dcd3f7699b40b09b455430fb63676338bc6b0"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
