name = "Vanilla + for Sunny"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1deb162828f17fd16cc54d5d0a86e20ba1ab1b47f254c45f518617efb012835a"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
