name = "Vanilla + for Sunny"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b642083dbc2da614a5d44d2a0eee77bf2bd959691403e7c215fe57ca9a3735b"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
