name = "Vanilla + for Sunny"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ba3f370d980c4c44b1a782791e61482737cac11c26d165dcd733b99fae3a064"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
