name = "Vanilla + for Sunny"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e40362cf294ae08ddfcd9cb94fd0d090ab1df4dbf10b4fc9dcb870c3c6efe73e"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
