name = "Vanilla + for Sunny"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12eef944a81665955509c03eb9d2e24e3e4d162abd3fb9542368ce0662ee33de"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
