name = "Vanilla + for Sunny"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4789e1b06eb0d2294a990b51fe088a105d23cab04f95fa2c5770a7d55123e84c"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
