name = "Ding"
filename = "Ding-1.16.5-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3222/705/Ding-1.16.5-1.3.0.jar"
hash-format = "murmur2"
hash = "862704897"

[update]
[update.curseforge]
file-id = 3222705
project-id = 231275
release-channel = "beta"
