name = "GeckoLib"
filename = "geckolib-forge-1.16.5-3.0.49.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3502/622/geckolib-forge-1.16.5-3.0.49.jar"
hash-format = "murmur2"
hash = "2708726135"

[update]
[update.curseforge]
file-id = 3502622
project-id = 388172
release-channel = "beta"
