name = "Repurposed Structures (Forge)"
filename = "repurposed_structures_forge-3.3.4+1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3499/509/repurposed_structures_forge-3.3.4+1.16.5.jar"
hash-format = "murmur2"
hash = "1774745774"

[update]
[update.curseforge]
file-id = 3499509
project-id = 368293
release-channel = "beta"
