name = "Valhelsia Core"
filename = "valhelsia_core-16.0.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3490/931/valhelsia_core-16.0.12.jar"
hash-format = "murmur2"
hash = "3381729081"

[update]
[update.curseforge]
file-id = 3490931
project-id = 416935
release-channel = "beta"
